set(_CATKIN_CURRENT_PACKAGE "dyros_jet")
set(dyros_jet_VERSION "0.1.0")
set(dyros_jet_MAINTAINER "Suhan Park <psh117@snu.ac.kr>")
set(dyros_jet_PACKAGE_FORMAT "1")
set(dyros_jet_BUILD_DEPENDS )
set(dyros_jet_BUILD_EXPORT_DEPENDS "dyros_jet_controller" "dyros_jet_msgs")
set(dyros_jet_BUILDTOOL_DEPENDS "catkin")
set(dyros_jet_BUILDTOOL_EXPORT_DEPENDS )
set(dyros_jet_EXEC_DEPENDS "dyros_jet_controller" "dyros_jet_msgs")
set(dyros_jet_RUN_DEPENDS "dyros_jet_controller" "dyros_jet_msgs")
set(dyros_jet_TEST_DEPENDS )
set(dyros_jet_DOC_DEPENDS )
set(dyros_jet_DEPRECATED "")